# -*- coding: utf-8 -*-
"""assignment 2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lyMXXyd08C5u-_DR8oYtiJ5PvJO3vzoV
"""

import random 
import time 

while  (1):
  temp = random.randint(0, 100)
  humidity = random.randint(0, 100)
  if temp>50:
    print("ALERT!! Detected temperature: "+str(temp)+"°C")
    break
    time.sleep(1)