# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ArIR8smK0iB9KrG7267ACLFfZOvqIjGQ
"""

import random

rand_temp=[]
rand_lhu=[]

n=10
for i in range(n):
  rand_temp.append(random.randint(20,40))
print("tempture",rand_temp)

for j in range(n):
   rand_lhu.append(random.randint(40,60))
print("humidity",rand_lhu)

for rand_temp in rand_temp:
  if rand_temp >=30 or rand_temp <=40:
    print("high temp",rand_temp)
  elif rand_temp  >=20 or rand_temp <=30:
    print("low temp",rand_temp)
  else:
    print()